/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCategoryDialog: typeof import('./src/components/activity-categories/ActivityCategoryDialog.vue')['default']
    AddOfficialAccount: typeof import('./src/components/AddOfficialAccount.vue')['default']
    AddTaskPanel: typeof import('./src/components/bank-card-activities/AddTaskPanel.vue')['default']
    BankCardActivityForm: typeof import('./src/components/bank-card-activities/BankCardActivityForm.vue')['default']
    BenefitPayPlatformDialog: typeof import('./src/components/benefit-pay-platforms/BenefitPayPlatformDialog.vue')['default']
    CardListDrawer: typeof import('./src/components/users/cards/CardListDrawer.vue')['default']
    CardPivotTable: typeof import('./src/components/users/cards/CardPivotTable.vue')['default']
    CardTemplateEditDialog: typeof import('./src/components/card-templates/CardTemplateEditDialog.vue')['default']
    CouponCategoryEditDialog: typeof import('./src/components/coupon-categories/CouponCategoryEditDialog.vue')['default']
    CouponPickerDialog: typeof import('./src/components/bank-card-activities/CouponPickerDialog.vue')['default']
    ParseTaskCard: typeof import('./src/components/bank-card-activities/ParseTaskCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TCheckboxGroup: typeof import('tdesign-vue-next')['CheckboxGroup']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDatePicker: typeof import('tdesign-vue-next')['DatePicker']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TEnhancedTable: typeof import('tdesign-vue-next')['EnhancedTable']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputGroup: typeof import('tdesign-vue-next')['InputGroup']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TOption: typeof import('tdesign-vue-next')['Option']
    TOptionGroup: typeof import('tdesign-vue-next')['OptionGroup']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    TTimePicker: typeof import('tdesign-vue-next')['TimePicker']
    UsagePlatformDialog: typeof import('./src/components/usage-platforms/UsagePlatformDialog.vue')['default']
  }
}
