/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/activity-categories/': RouteRecordInfo<
      '/activity-categories/',
      '/activity-categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bank-card-activities/edit/': RouteRecordInfo<
      '/bank-card-activities/edit/',
      '/bank-card-activities/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bank-card-activities/web/': RouteRecordInfo<
      '/bank-card-activities/web/',
      '/bank-card-activities/web',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bank-card-activities/wechat/': RouteRecordInfo<
      '/bank-card-activities/wechat/',
      '/bank-card-activities/wechat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/banks/': RouteRecordInfo<
      '/banks/',
      '/banks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/benefit-pay-platforms/': RouteRecordInfo<
      '/benefit-pay-platforms/',
      '/benefit-pay-platforms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/card-templates/': RouteRecordInfo<
      '/card-templates/',
      '/card-templates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/card-templates/components/BankItem': RouteRecordInfo<
      '/card-templates/components/BankItem',
      '/card-templates/components/BankItem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/card-templates/components/BankSidebar': RouteRecordInfo<
      '/card-templates/components/BankSidebar',
      '/card-templates/components/BankSidebar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/card-templates/components/CardEditDialog': RouteRecordInfo<
      '/card-templates/components/CardEditDialog',
      '/card-templates/components/CardEditDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/card-templates/components/CardGrid': RouteRecordInfo<
      '/card-templates/components/CardGrid',
      '/card-templates/components/CardGrid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/card-templates/components/CardItem': RouteRecordInfo<
      '/card-templates/components/CardItem',
      '/card-templates/components/CardItem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/card-templates/credit': RouteRecordInfo<
      '/card-templates/credit',
      '/card-templates/credit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/card-templates/debit': RouteRecordInfo<
      '/card-templates/debit',
      '/card-templates/debit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/coupon-categories/': RouteRecordInfo<
      '/coupon-categories/',
      '/coupon-categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/usage-platforms/': RouteRecordInfo<
      '/usage-platforms/',
      '/usage-platforms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user-feedbacks/': RouteRecordInfo<
      '/user-feedbacks/',
      '/user-feedbacks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/cards/': RouteRecordInfo<
      '/users/cards/',
      '/users/cards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/activity-categories/index.vue': {
      routes:
        | '/activity-categories/'
      views:
        | never
    }
    'src/pages/bank-card-activities/edit/index.vue': {
      routes:
        | '/bank-card-activities/edit/'
      views:
        | never
    }
    'src/pages/bank-card-activities/web/index.vue': {
      routes:
        | '/bank-card-activities/web/'
      views:
        | never
    }
    'src/pages/bank-card-activities/wechat/index.vue': {
      routes:
        | '/bank-card-activities/wechat/'
      views:
        | never
    }
    'src/pages/banks/index.vue': {
      routes:
        | '/banks/'
      views:
        | never
    }
    'src/pages/benefit-pay-platforms/index.vue': {
      routes:
        | '/benefit-pay-platforms/'
      views:
        | never
    }
    'src/pages/card-templates/index.vue': {
      routes:
        | '/card-templates/'
      views:
        | never
    }
    'src/pages/card-templates/components/BankItem.vue': {
      routes:
        | '/card-templates/components/BankItem'
      views:
        | never
    }
    'src/pages/card-templates/components/BankSidebar.vue': {
      routes:
        | '/card-templates/components/BankSidebar'
      views:
        | never
    }
    'src/pages/card-templates/components/CardEditDialog.vue': {
      routes:
        | '/card-templates/components/CardEditDialog'
      views:
        | never
    }
    'src/pages/card-templates/components/CardGrid.vue': {
      routes:
        | '/card-templates/components/CardGrid'
      views:
        | never
    }
    'src/pages/card-templates/components/CardItem.vue': {
      routes:
        | '/card-templates/components/CardItem'
      views:
        | never
    }
    'src/pages/card-templates/credit.vue': {
      routes:
        | '/card-templates/credit'
      views:
        | never
    }
    'src/pages/card-templates/debit.vue': {
      routes:
        | '/card-templates/debit'
      views:
        | never
    }
    'src/pages/coupon-categories/index.vue': {
      routes:
        | '/coupon-categories/'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/usage-platforms/index.vue': {
      routes:
        | '/usage-platforms/'
      views:
        | never
    }
    'src/pages/user-feedbacks/index.vue': {
      routes:
        | '/user-feedbacks/'
      views:
        | never
    }
    'src/pages/users/cards/index.vue': {
      routes:
        | '/users/cards/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
